const providers = {
  openai:{name:'OpenAI',base:'https://api.openai.com/v1',models:['gpt-4o','gpt-4o-mini','gpt-4.1','gpt-4.1-mini','o3-mini'],hint:'Official OpenAI API · chat completions'},
  grok:{name:'Grok',base:'https://api.x.ai/v1',models:['grok-3','grok-3-mini','grok-2-latest'],hint:'xAI API · OpenAI-compatible'},
  claude:{name:'Claude',base:'https://api.anthropic.com/v1',models:['claude-sonnet-4-20250514','claude-3-7-sonnet-latest','claude-3-5-haiku-latest'],hint:'Anthropic Messages API · direct browser calls may require CORS'},
  gemini:{name:'Gemini',base:'https://generativelanguage.googleapis.com/v1beta',models:['gemini-2.5-pro','gemini-2.5-flash','gemini-2.0-flash'],hint:'Google AI Studio · native generateContent'},
  openrouter:{name:'OpenRouter',base:'https://openrouter.ai/api/v1',models:['openai/gpt-4o-mini','anthropic/claude-3.7-sonnet','google/gemini-2.5-flash','deepseek/deepseek-chat'],hint:'Multi-model gateway · 300+ models'},
  together:{name:'Together AI',base:'https://api.together.xyz/v1',models:['meta-llama/Llama-3.3-70B-Instruct-Turbo','Qwen/Qwen2.5-72B-Instruct-Turbo','deepseek-ai/DeepSeek-V3'],hint:'Open-source models at scale'},
  fireworks:{name:'Fireworks AI',base:'https://api.fireworks.ai/inference/v1',models:['accounts/fireworks/models/llama-v3p1-70b-instruct','accounts/fireworks/models/mixtral-8x22b-instruct-v0p1'],hint:'Fast open-source inference'},
  groq:{name:'Groq',base:'https://api.groq.com/openai/v1',models:['llama-3.3-70b-versatile','llama-3.1-8b-instant','deepseek-r1-distill-llama-70b'],hint:'Ultra-fast inference · OpenAI-compatible'},
  deepseek:{name:'DeepSeek',base:'https://api.deepseek.com/v1',models:['deepseek-chat','deepseek-reasoner'],hint:'Reasoning and chat models'},
  mistral:{name:'Mistral',base:'https://api.mistral.ai/v1',models:['mistral-large-latest','mistral-small-latest','codestral-latest'],hint:'Mistral AI platform'},
  custom:{name:'Custom / OpenAI-compatible',base:'',models:['custom-model'],hint:'Any endpoint exposing POST /chat/completions'}
};
const $=s=>document.querySelector(s); const provider=$('#provider'), model=$('#model'), baseUrl=$('#baseUrl'), apiKey=$('#apiKey'), prompt=$('#prompt'), responseArea=$('#responseArea');
let controller=null; let history=JSON.parse(localStorage.getItem('prism-history')||'[]');
Object.entries(providers).forEach(([key,p])=>{const option=document.createElement('option');option.value=key;option.textContent=p.name;provider.append(option)});
function updateProvider(){const p=providers[provider.value]; model.innerHTML='';p.models.forEach(m=>{const o=document.createElement('option');o.value=m;o.textContent=m;model.append(o)});baseUrl.value=p.base;$('#providerHint').textContent=p.hint;$('#modelBadge').textContent=model.value;localStorage.setItem('prism-provider',provider.value)}
 provider.addEventListener('change',updateProvider);model.addEventListener('change',()=>$('#modelBadge').textContent=model.value);
function setModelOptions(ids){model.innerHTML='';ids.forEach(id=>{const o=document.createElement('option');o.value=id;o.textContent=id;model.append(o)});if(ids.length)$('#modelBadge').textContent=ids[0]}
function extractModelIds(data){const list=Array.isArray(data)?data:(data.data||data.models||data.items||[]);return list.map(item=>typeof item==='string'?item:(item.id||item.name||item.model||item.slug)).filter(Boolean).map(id=>String(id).replace(/^models\//,''))}
function normalizeBaseUrl(value){return value.trim().replace(/\/+$/,'').replace(/\/(chat\/completions|responses|models)$/i,'')}
async function fetchModels(){const button=$('#fetchModels'),status=$('#modelFetchStatus'),key=provider.value,p=providers[key],url=normalizeBaseUrl(baseUrl.value||p.base);if(!url)return showError('Add a base URL before fetching models.');if(!apiKey.value.trim())return showError('Add your API key before fetching private models.');clearError();button.disabled=true;button.textContent='↻ loading…';status.className='field-hint';status.textContent='Checking your endpoint for model IDs…';try{let headers={Authorization:`Bearer ${apiKey.value}`,Accept:'application/json'},candidates=[];if(key==='gemini')candidates=[`${url}/models?key=${encodeURIComponent(apiKey.value)}`];else{candidates=[`${url}/models`];const parsed=new URL(url);if(!/\/v\d+(?:beta)?$/i.test(parsed.pathname))candidates.push(`${url}/v1/models`)}let lastError;for(const endpoint of candidates){const res=await fetch(endpoint,{headers});if(res.ok){const data=await readResponse(res),ids=extractModelIds(data);if(ids.length){setModelOptions(ids);status.className='field-hint fetch-success';status.textContent=`Found ${ids.length} model${ids.length===1?'':'s'} · dropdown updated`;localStorage.setItem('prism-models',JSON.stringify({url,ids}));return}lastError=new Error('The endpoint responded, but no model IDs were found.')}else{const data=await res.text();lastError=new Error(`${res.status} ${res.statusText}${data?` · ${data.slice(0,140)}`:''}`)}}throw lastError||new Error('No model endpoint responded.')}catch(error){const message=error.name==='TypeError'?'Could not reach endpoint. Check the URL, HTTPS, and whether the API allows browser CORS requests.':error.message;status.className='field-hint fetch-error';status.textContent=message;showError(`Model discovery failed: ${message}`)}finally{button.disabled=false;button.textContent='↻ fetch models'}}
$('#fetchModels').addEventListener('click',fetchModels);
const savedProvider=localStorage.getItem('prism-provider');if(savedProvider&&providers[savedProvider])provider.value=savedProvider;updateProvider();
$('#toggleKey').addEventListener('click',()=>{apiKey.type=apiKey.type==='password'?'text':'password';$('#toggleKey').textContent=apiKey.type==='password'?'show':'hide'});
prompt.addEventListener('input',()=>$('#charCount').textContent=`${prompt.value.length.toLocaleString()} / 8,000`);
prompt.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key==='Enter'){e.preventDefault();send()}});
function showError(message){const box=$('#errorBanner');box.textContent=message;box.classList.remove('hidden')};function clearError(){$('#errorBanner').classList.add('hidden')}
function setLoading(loading){$('#sendButton').disabled=loading;$('#sendButton').innerHTML=loading?'<span class="spinner"></span><span>Thinking…</span>':'<span class="send-icon">↗</span><span>Send prompt</span><span class="shortcut">⌘ ↵</span>';$('#stopButton').classList.toggle('hidden',!loading)}
function authHeaders(){return provider.value==='claude'?{'x-api-key':apiKey.value,'anthropic-version':'2023-06-01'}:{Authorization:`Bearer ${apiKey.value}`,'Content-Type':'application/json'}}
async function callApi(text){const key=provider.value,p=providers[key],url=(baseUrl.value||p.base).replace(/\/$/,'');if(key==='gemini'){const res=await fetch(`${url}/models/${encodeURIComponent(model.value)}:generateContent?key=${encodeURIComponent(apiKey.value)}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text}]}]}) ,signal:controller.signal});const data=await readResponse(res);return data.candidates?.[0]?.content?.parts?.map(x=>x.text).join('')||JSON.stringify(data)}if(key==='claude'){const res=await fetch(`${url}/messages`,{method:'POST',headers:authHeaders(),body:JSON.stringify({model:model.value,max_tokens:2048,messages:[{role:'user',content:text}]}),signal:controller.signal});const data=await readResponse(res);return data.content?.map(x=>x.text||'').join('')||JSON.stringify(data)}const res=await fetch(`${url}/chat/completions`,{method:'POST',headers:authHeaders(),body:JSON.stringify({model:model.value,messages:[{role:'user',content:text}],temperature:.7}),signal:controller.signal});const data=await readResponse(res);return data.choices?.[0]?.message?.content||JSON.stringify(data)}
async function readResponse(res){const raw=await res.text();let data;try{data=JSON.parse(raw)}catch{data={error:{message:raw||`Request failed (${res.status})`}}}if(!res.ok)throw new Error(data.error?.message||data.message||`Request failed with status ${res.status}`);return data}
async function send(){clearError();const text=prompt.value.trim();if(!text)return showError('Write a prompt before sending.');if(!apiKey.value.trim())return showError('Add your API key to connect. It is used only for this request.');if(!baseUrl.value.trim())return showError('Add a base URL for the custom provider.');const started=Date.now();controller=new AbortController();setLoading(true);responseArea.innerHTML='<div class="loading-state"><span class="spinner large"></span><p>Connecting to the model…</p></div>';$('#responseMeta').textContent=`${providers[provider.value].name} / ${model.value}`;try{const answer=await callApi(text);responseArea.textContent=answer;$('#responseTime').textContent=`${((Date.now()-started)/1000).toFixed(1)}s response`;history.unshift({prompt:text,answer,provider:providers[provider.value].name,model:model.value,time:new Date().toISOString()});history=history.slice(0,20);localStorage.setItem('prism-history',JSON.stringify(history));renderHistory()}catch(error){if(error.name!=='AbortError')showError(error.message||'Something went wrong. Check your key, model, URL, and browser CORS access.');responseArea.innerHTML='<div class="empty-state"><span class="empty-orbit">⌁</span><p>No response received.</p><small>Check the connection details and try again.</small></div>'}finally{controller=null;setLoading(false)}}
$('#sendButton').addEventListener('click',send);$('#stopButton').addEventListener('click',()=>controller?.abort());
function renderHistory(){const list=$('#historyList');if(!history.length){list.innerHTML='<div class="history-empty">No saved conversations yet. Your latest exchanges will appear here.</div>';return}list.innerHTML=history.map((h,i)=>`<div class="history-item" data-index="${i}"><div><div class="history-prompt">${escapeHtml(h.prompt)}</div><div class="history-provider">${escapeHtml(h.provider)} · ${escapeHtml(h.model)}</div></div><span class="history-meta">${new Date(h.time).toLocaleDateString(undefined,{month:'short',day:'numeric'})} ↗</span></div>`).join('');list.querySelectorAll('.history-item').forEach(el=>el.addEventListener('click',()=>{const h=history[el.dataset.index];prompt.value=h.prompt;prompt.dispatchEvent(new Event('input'));responseArea.textContent=h.answer;$('#responseMeta').textContent=`${h.provider} / ${h.model}`;window.scrollTo({top:document.querySelector('.conversation-card').offsetTop-20,behavior:'smooth'})}))}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function clearHistory(){history=[];localStorage.removeItem('prism-history');renderHistory()}$('#clearHistory').addEventListener('click',clearHistory);$('#clearAll').addEventListener('click',()=>{clearHistory();prompt.value='';prompt.dispatchEvent(new Event('input'));responseArea.innerHTML='<div class="empty-state"><span class="empty-orbit">✦</span><p>Your response will materialize here.</p><small>Configure a provider, then send a prompt to begin.</small></div>'});renderHistory();
