import * as pdfjsLib from './vendor/pdf.min.mjs';

pdfjsLib.GlobalWorkerOptions.workerSrc = './vendor/pdf.worker.min.mjs';
const { PDFDocument, rgb, degrees, StandardFonts } = window.PDFLib;
const $ = (selector, root = document) => root.querySelector(selector);
const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];

const state = { bytes:null, pdfjs:null, pdfDoc:null, pages:[], current:0, zoom:1, tool:'select', history:[], future:[], selected:new Set(), pending:null, drawing:null, shape:'rectangle', signatureImage:null, fileName:'Untitled.pdf' };
const els = { landing:$('#landingState'), editor:$('#editorState'), canvas:$('#pdfCanvas'), overlay:$('#overlayCanvas'), stage:$('#pageStage'), area:$('#canvasArea'), empty:$('#canvasEmpty'), thumbs:$('#thumbList'), fileName:$('#fileName'), fileMeta:$('#fileMeta'), pageCount:$('#pageCount'), total:$('#totalPages'), current:$('#currentPage'), zoom:$('#zoomLabel'), save:$('#savePdfBtn'), download:$('#downloadBtn'), toast:$('#toast'), textDialog:$('#textDialog'), shapeDialog:$('#shapeDialog'), signatureDialog:$('#signatureDialog'), signatureCanvas:$('#signatureCanvas') };

function clonePages(pages){ return pages.map(p=>({...p,annotations:(p.annotations||[]).map(a=>({...a,points:a.points?.map(pt=>({...pt}))}))})); }
function snapshot(){ return {pages:clonePages(state.pages),current:state.current,selected:[...state.selected]}; }
function restore(s){ state.pages=clonePages(s.pages); state.current=Math.min(s.current,state.pages.length-1); state.selected=new Set(s.selected); renderAll(); }
function mutate(fn){ state.history.push(snapshot()); if(state.history.length>60)state.history.shift(); state.future=[]; fn(); renderAll(); }
function toast(message){ els.toast.textContent=message; els.toast.classList.add('show'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>els.toast.classList.remove('show'),2800); }
function errorToast(message){ toast(`⚠ ${message}`); }
function hexRgb(hex){ const n=parseInt(hex.slice(1),16); return rgb(((n>>16)&255)/255,((n>>8)&255)/255,(n&255)/255); }
function pageSize(page){ return page.blank ? {width:612,height:792} : {width:page.width||612,height:page.height||792}; }
function currentPage(){ return state.pages[state.current]; }
function pageModel(sourceIndex, blank=false){return {sourceIndex,blank,rotation:0,width:blank?612:undefined,height:blank?792:undefined,annotations:[]};}

async function loadPdf(bytes, name='document.pdf'){
  try{
    const clean = new Uint8Array(bytes);
    const [pdfjsDoc,pdfDoc] = await Promise.all([pdfjsLib.getDocument({data:clean.slice(0)}).promise, PDFDocument.load(clean)]);
    state.bytes=clean; state.pdfjs=pdfjsDoc; state.pdfDoc=pdfDoc; state.pages=Array.from({length:pdfDoc.getPageCount()},(_,i)=>pageModel(i)); state.current=0; state.history=[]; state.future=[]; state.selected.clear(); state.fileName=name||'document.pdf';
    for(const p of state.pages){ const pg=pdfDoc.getPage(p.sourceIndex); const box=pg.getSize(); p.width=box.width; p.height=box.height; }
    els.landing.hidden=true; els.editor.hidden=false; els.save.disabled=false; els.download.disabled=false; els.fileName.textContent=state.fileName; els.fileMeta.textContent=`${formatBytes(clean.byteLength)} · ${state.pages.length} pages`; renderAll(); toast('PDF opened locally');
  }catch(error){ console.error(error); errorToast('This PDF is corrupted, encrypted, or unsupported.'); }
}
function formatBytes(bytes){if(bytes<1024)return `${bytes} B`;if(bytes<1048576)return `${(bytes/1024).toFixed(0)} KB`;return `${(bytes/1048576).toFixed(1)} MB`;}
function renderAll(){ if(!state.pages.length)return; els.pageCount.textContent=state.pages.length; els.total.textContent=state.pages.length; els.current.textContent=state.current+1; els.zoom.textContent=`${Math.round(state.zoom*100)}%`; els.fileMeta.textContent=`${formatBytes(state.bytes?.byteLength||0)} · ${state.pages.length} pages`; renderThumbs(); renderPage(); }
async function renderThumbs(){
  els.thumbs.innerHTML='';
  for(let i=0;i<state.pages.length;i++){
    const page=state.pages[i], item=document.createElement('div'); item.className=`thumb ${i===state.current?'active':''}`; item.draggable=true; item.dataset.index=i;
    const check=document.createElement('input'); check.type='checkbox'; check.title='Select page for extraction'; check.checked=state.selected.has(i); check.addEventListener('click',e=>{e.stopPropagation();check.checked?state.selected.add(i):state.selected.delete(i); updateSelectionInfo();}); item.append(check);
    const canvas=document.createElement('canvas'); const size=pageSize(page), scale=150/size.width; canvas.width=150; canvas.height=Math.round(size.height*scale); item.append(canvas);
    const label=document.createElement('div'); label.className='thumb-label'; label.innerHTML=`<span>Page ${i+1}</span><span>${page.rotation||0}°</span>`; item.append(label); item.addEventListener('click',()=>{state.current=i;renderAll();});
    item.addEventListener('dragstart',()=>{item.classList.add('dragging');state.dragIndex=i}); item.addEventListener('dragend',()=>item.classList.remove('dragging')); item.addEventListener('dragover',e=>e.preventDefault()); item.addEventListener('drop',e=>{e.preventDefault();const from=state.dragIndex,to=i;if(from!==to)mutate(()=>{const [moved]=state.pages.splice(from,1);state.pages.splice(to,0,moved);state.current=to;});}); els.thumbs.append(item);
    if(page.blank){const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#e4e7ed';ctx.strokeRect(0,0,canvas.width,canvas.height);} else {try{const pdfPage=await state.pdfjs.getPage(page.sourceIndex+1);const viewport=pdfPage.getViewport({scale});await pdfPage.render({canvasContext:canvas.getContext('2d'),viewport}).promise;}catch(e){}}
  }
  updateSelectionInfo();
}
async function renderPage(){
  const page=currentPage(); if(!page)return; els.empty.style.display='none'; els.stage.style.display='block';
  const size=pageSize(page), baseScale=Math.min(1.35,Math.max(.55,(els.area.clientWidth-75)/size.width)), scale=baseScale*state.zoom; let viewport={width:size.width*scale,height:size.height*scale};
  if(!page.blank){const pdfPage=await state.pdfjs.getPage(page.sourceIndex+1);viewport=pdfPage.getViewport({scale});els.canvas.width=Math.ceil(viewport.width);els.canvas.height=Math.ceil(viewport.height);await pdfPage.render({canvasContext:els.canvas.getContext('2d'),viewport}).promise;}else{els.canvas.width=Math.ceil(viewport.width);els.canvas.height=Math.ceil(viewport.height);const ctx=els.canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,els.canvas.width,els.canvas.height);}
  els.overlay.width=els.canvas.width; els.overlay.height=els.canvas.height; els.stage.style.width=`${els.canvas.width}px`;els.stage.style.height=`${els.canvas.height}px`; drawOverlay();
}
function drawOverlay(){const ctx=els.overlay.getContext('2d');ctx.clearRect(0,0,els.overlay.width,els.overlay.height);const page=currentPage();if(!page)return; const sx=els.overlay.width,sy=els.overlay.height;
  for(const a of page.annotations){ctx.save();ctx.globalAlpha=a.opacity??1;ctx.strokeStyle=a.color||'#2358d9';ctx.fillStyle=a.fill||'transparent';ctx.lineWidth=(a.lineWidth||2)*Math.max(1,state.zoom);ctx.lineCap='round';ctx.lineJoin='round';
    if(a.type==='draw'){ctx.beginPath();a.points.forEach((p,i)=>i?ctx.lineTo(p.x*sx,p.y*sy):ctx.moveTo(p.x*sx,p.y*sy));ctx.stroke();}
    if(a.type==='highlight'){ctx.fillStyle=a.color||'#ffe16b';ctx.globalAlpha=.32;ctx.fillRect(a.x*sx,a.y*sy,a.w*sx,a.h*sy);}
    if(a.type==='rect'){ctx.strokeRect(a.x*sx,a.y*sy,a.w*sx,a.h*sy);}
    if(a.type==='circle'){ctx.beginPath();ctx.ellipse((a.x+a.w/2)*sx,(a.y+a.h/2)*sy,Math.abs(a.w*sx/2),Math.abs(a.h*sy/2),0,0,Math.PI*2);ctx.stroke();}
    if(a.type==='line'||a.type==='arrow'){const x1=a.x*sx,y1=a.y*sy,x2=(a.x+a.w)*sx,y2=(a.y+a.h)*sy;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();if(a.type==='arrow'){const ang=Math.atan2(y2-y1,x2-x1);ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-12*Math.cos(ang-.45),y2-12*Math.sin(ang-.45));ctx.moveTo(x2,y2);ctx.lineTo(x2-12*Math.cos(ang+.45),y2-12*Math.sin(ang+.45));ctx.stroke();}}
    if(a.type==='text'){ctx.fillStyle=a.color||'#182033';ctx.font=`${a.italic?'italic ':''}${a.bold?'700 ':'400 '}${a.size*scale}px ${a.font||'Helvetica'}`;ctx.textAlign=a.align||'left';a.text.split('\n').forEach((line,i)=>ctx.fillText(line,(a.x+(a.align==='center'?a.w/2:a.align==='right'?a.w:0))*sx,(a.y+(i+1)*a.size/size.height)*sy));}
    if(a.type==='image'||a.type==='signature'){if(a.image){const img=new Image();img.onload=()=>{ctx.drawImage(img,a.x*sx,a.y*sy,a.w*sx,a.h*sy)};img.src=a.image;}}
    if(a.selected){ctx.setLineDash([5,4]);ctx.strokeStyle='#2358d9';ctx.strokeRect(a.x*sx-4,a.y*sy-4,(a.w||.08)*sx+8,(a.h||.05)*sy+8);ctx.setLineDash([]);}ctx.restore();
  }
}
function pointerPos(e){const rect=els.overlay.getBoundingClientRect();return {x:Math.max(0,Math.min(1,(e.clientX-rect.left)/rect.width)),y:Math.max(0,Math.min(1,(e.clientY-rect.top)/rect.height))};}
function clearSelections(){currentPage()?.annotations.forEach(a=>a.selected=false);}
function beginTool(e){if(!currentPage())return;const p=pointerPos(e), tool=state.tool;if(tool==='select'){clearSelections();const found=[...currentPage().annotations].reverse().find(a=>p.x>=(a.x||0)&&p.x<=(a.x+(a.w||.08))&&p.y>=(a.y||0)&&p.y<=(a.y+(a.h||.08)));if(found)found.selected=true;drawOverlay();return} if(tool==='text'||tool==='image'||tool==='signature'){state.pending=p;if(tool==='text')els.textDialog.showModal();if(tool==='image')$('#imageInput').click();if(tool==='signature')els.signatureDialog.showModal();return} state.drawing={start:p,points:[p]};els.stage.classList.add('interactive');}
function moveTool(e){if(!state.drawing)return;const p=pointerPos(e),tool=state.tool;if(tool==='draw')state.drawing.points.push(p);drawOverlay();const ctx=els.overlay.getContext('2d');ctx.save();ctx.strokeStyle=tool==='highlight'?'#ffe16b':'#2358d9';ctx.globalAlpha=tool==='highlight'?.32:1;ctx.lineWidth=tool==='highlight'?18:2;ctx.beginPath();if(tool==='draw'){state.drawing.points.forEach((pt,i)=>i?ctx.lineTo(pt.x*els.overlay.width,pt.y*els.overlay.height):ctx.moveTo(pt.x*els.overlay.width,pt.y*els.overlay.height));}else{ctx.rect(state.drawing.start.x*els.overlay.width,state.drawing.start.y*els.overlay.height,(p.x-state.drawing.start.x)*els.overlay.width,(p.y-state.drawing.start.y)*els.overlay.height);}ctx.stroke();ctx.restore();}
function endTool(e){if(!state.drawing)return;const end=pointerPos(e),start=state.drawing.start,tool=state.tool;state.drawing=null;els.stage.classList.remove('interactive');if(Math.abs(end.x-start.x)<.01&&Math.abs(end.y-start.y)<.01)return;mutate(()=>{const p=currentPage();if(tool==='draw')p.annotations.push({type:'draw',points:state.drawing?.points||[start,end],color:'#2358d9',lineWidth:2});else if(tool==='highlight')p.annotations.push({type:'highlight',x:Math.min(start.x,end.x),y:Math.min(start.y,end.y),w:Math.abs(end.x-start.x),h:Math.abs(end.y-start.y),color:'#ffe16b'});else p.annotations.push({type:state.shape,x:start.x,y:start.y,w:end.x-start.x,h:end.y-start.y,color:$('#shapeColor').value,lineWidth:+$('#shapeWidth').value});});}
// Capture draw points before state is cleared.
const originalEnd=endTool;
els.overlay.addEventListener('pointerdown',e=>{if(['draw','highlight','shape'].includes(state.tool)){const p=pointerPos(e);state.drawing={start:p,points:[p]};els.overlay.setPointerCapture(e.pointerId);els.stage.classList.add('interactive');}else beginTool(e);});
els.overlay.addEventListener('pointermove',e=>{if(state.drawing)moveTool(e)});
els.overlay.addEventListener('pointerup',e=>{if(!state.drawing)return;const draft=state.drawing;const end=pointerPos(e);state.drawing=null;els.stage.classList.remove('interactive');if(Math.abs(end.x-draft.start.x)<.01&&Math.abs(end.y-draft.start.y)<.01)return;mutate(()=>{const p=currentPage(),tool=state.tool;if(tool==='draw')p.annotations.push({type:'draw',points:draft.points.concat([end]),color:'#2358d9',lineWidth:2});else if(tool==='highlight')p.annotations.push({type:'highlight',x:Math.min(draft.start.x,end.x),y:Math.min(draft.start.y,end.y),w:Math.abs(end.x-draft.start.x),h:Math.abs(end.y-draft.start.y),color:'#ffe16b'});else p.annotations.push({type:state.shape,x:draft.start.x,y:draft.start.y,w:end.x-draft.start.x,h:end.y-draft.start.y,color:$('#shapeColor').value,lineWidth:+$('#shapeWidth').value});});});

function setTool(tool){state.tool=tool;$$('.tool[data-tool]').forEach(b=>b.classList.toggle('active',b.dataset.tool===tool));if(tool==='shape')els.shapeDialog.showModal();}
$$('.tool[data-tool]').forEach(b=>b.addEventListener('click',()=>setTool(b.dataset.tool)));
$('#undoBtn').addEventListener('click',()=>{if(state.history.length){state.future.push(snapshot());restore(state.history.pop());}});$('#redoBtn').addEventListener('click',()=>{if(state.future.length){state.history.push(snapshot());restore(state.future.pop());}});
$('#zoomIn').addEventListener('click',()=>{state.zoom=Math.min(3,state.zoom+.15);renderPage();});$('#zoomOut').addEventListener('click',()=>{state.zoom=Math.max(.5,state.zoom-.15);renderPage();});
$('#prevPage').addEventListener('click',()=>{if(state.current>0){state.current--;renderAll();}});$('#nextPage').addEventListener('click',()=>{if(state.current<state.pages.length-1){state.current++;renderAll();}});
$('#rotatePageBtn').addEventListener('click',()=>mutate(()=>{currentPage().rotation=(currentPage().rotation+90)%360;}));
$('#addPageBtn').addEventListener('click',()=>mutate(()=>{state.pages.splice(state.current+1,0,pageModel(null,true));state.current++;}));
$('#duplicatePageBtn').addEventListener('click',()=>mutate(()=>{const copy=clonePages([currentPage()])[0];state.pages.splice(state.current+1,0,copy);state.current++;}));
$('#deletePageBtn').addEventListener('click',()=>{if(state.pages.length<=1)return errorToast('A PDF must have at least one page.');mutate(()=>{state.pages.splice(state.current,1);state.current=Math.max(0,state.current-1);});});
$('#textForm').addEventListener('submit',e=>{e.preventDefault();const p=state.pending||{x:.15,y:.15};mutate(()=>currentPage().annotations.push({type:'text',x:p.x,y:p.y,w:.7,h:.1,text:$('#textValue').value,font:$('#textFont').value,size:+$('#textSize').value,color:$('#textColor').value,align:$('#textAlign').value,bold:$('#textBold').checked,italic:$('#textItalic').checked}));$('#textDialog').close();$('#textValue').value='';state.pending=null;});
$$('[data-shape]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();state.shape=b.dataset.shape;els.shapeDialog.close();$$('.tool[data-tool]').forEach(t=>t.classList.toggle('active',t.dataset.tool==='shape'));state.tool='shape';toast(`Draw a ${state.shape} on the page`);}));
$('#imageInput').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;if(e.target.dataset.signature==='1'){const r=new FileReader();r.onload=()=>{state.signatureImage=r.result;$('#signatureFileName').textContent=file.name;};r.readAsDataURL(file);delete e.target.dataset.signature;e.target.value='';return;}const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const ratio=img.height/img.width;mutate(()=>currentPage().annotations.push({type:'image',x:state.pending?.x||.2,y:state.pending?.y||.2,w:.3,h:.3*ratio,image:reader.result}));};img.src=reader.result;};reader.readAsDataURL(file);e.target.value='';});
function setupSignature(){const c=els.signatureCanvas,ctx=c.getContext('2d');ctx.lineWidth=3;ctx.lineCap='round';ctx.strokeStyle='#182033';let drawing=false;c.onpointerdown=e=>{drawing=true;ctx.beginPath();ctx.moveTo(e.offsetX,e.offsetY);c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(drawing){ctx.lineTo(e.offsetX,e.offsetY);ctx.stroke()}};c.onpointerup=()=>drawing=false;$('#clearSignature').onclick=()=>ctx.clearRect(0,0,c.width,c.height);}
setupSignature();
$$('[data-sign-tab]').forEach(tab=>tab.addEventListener('click',()=>{$$('[data-sign-tab]').forEach(t=>t.classList.toggle('active',t===tab));$$('[data-sign-panel]').forEach(p=>p.classList.toggle('hidden',p.dataset.signPanel!==tab.dataset.signTab));state.signTab=tab.dataset.signTab;}));
$('#signatureUploadBtn').addEventListener('click',()=>{$('#imageInput').dataset.signature='1';$('#imageInput').click();});
$('#signatureForm').addEventListener('submit',e=>{e.preventDefault();let image;if(state.signTab==='draw')image=els.signatureCanvas.toDataURL('image/png');else if(state.signTab==='type'){const c=document.createElement('canvas');c.width=700;c.height=180;const x=c.getContext('2d');x.fillStyle='#182033';x.font=`72px ${$('#signatureFont').value}`;x.fillText($('#signatureText').value||'Signature',20,110);image=c.toDataURL('image/png');}else image=state.signatureImage;if(!image)return errorToast('Choose or draw a signature first.');const im=new Image();im.onload=()=>{const ratio=im.height/im.width;mutate(()=>currentPage().annotations.push({type:'signature',x:state.pending?.x||.2,y:state.pending?.y||.2,w:.32,h:.32*ratio,image}));els.signatureDialog.close();};im.src=image;});

async function exportPdfBytes(onlyIndexes=null){const out=await PDFDocument.create(),fontCache={};const indexes=onlyIndexes||state.pages.map((_,i)=>i);for(const idx of indexes){const meta=state.pages[idx];let page;if(meta.blank)page=out.addPage([meta.width||612,meta.height||792]);else{[page]=await out.copyPages(state.pdfDoc,[meta.sourceIndex]);out.addPage(page);}if(meta.rotation)page.setRotation(degrees(meta.rotation));const {width,height}=page.getSize();for(const a of meta.annotations){const x=a.x*width,y=height-(a.y*height),w=a.w*width,h=a.h*height;if(a.type==='text'){const key=`${a.font}-${a.bold}-${a.italic}`;fontCache[key] ||= await out.embedFont(StandardFonts[a.font]||StandardFonts.Helvetica);const f=fontCache[key],size=a.size;const tw=f.widthOfTextAtSize(a.text,size);let tx=x;if(a.align==='center')tx=x+w/2-tw/2;if(a.align==='right')tx=x+w-tw;const lines=a.text.split('\n');lines.forEach((line,i)=>page.drawText(line,{x:tx,y:y-(i+1)*size,font:f,size,color:hexRgb(a.color||'#182033')}));}else if(a.type==='highlight'){page.drawRectangle({x,y:y-h,width:w,height:h,color:hexRgb('#ffe16b'),opacity:.34,borderOpacity:0});}else if(a.type==='rect'){page.drawRectangle({x,y:y-h,width:w,height:h,borderColor:hexRgb(a.color||'#2358d9'),borderWidth:a.lineWidth||2});}else if(a.type==='circle'){page.drawEllipse({x:x+w/2,y:y-h/2,xScale:Math.abs(w/2),yScale:Math.abs(h/2),borderColor:hexRgb(a.color||'#2358d9'),borderWidth:a.lineWidth||2});}else if(a.type==='line'||a.type==='arrow'){page.drawLine({start:{x,y},end:{x:x+w,y:y-h},thickness:a.lineWidth||2,color:hexRgb(a.color||'#2358d9')});}else if(a.type==='draw'){for(let i=1;i<a.points.length;i++){const p1=a.points[i-1],p2=a.points[i];page.drawLine({start:{x:p1.x*width,y:height-p1.y*height},end:{x:p2.x*width,y:height-p2.y*height},thickness:a.lineWidth||2,color:hexRgb(a.color||'#2358d9')});}}else if(a.type==='image'||a.type==='signature'){const imageBytes=await fetch(a.image).then(r=>r.arrayBuffer());const emb=a.image.includes('image/jpeg')?await out.embedJpg(imageBytes):await out.embedPng(imageBytes);page.drawImage(emb,{x,y:y-h,width:w,height:h});}}
  }return out.save();}
async function download(bytes,name){const blob=new Blob([bytes],{type:'application/pdf'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
$('#downloadBtn').addEventListener('click',async()=>{try{const bytes=await exportPdfBytes();await download(bytes,state.fileName.replace(/\.pdf$/i,'')+'-edited.pdf');toast('PDF downloaded');}catch(e){console.error(e);errorToast('Could not export this PDF.');}});$('#savePdfBtn').addEventListener('click',()=>$('#downloadBtn').click());
$('#extractBtn').addEventListener('click',async()=>{if(!state.selected.size)return errorToast('Select pages using the checkboxes first.');const indexes=[...state.selected].sort((a,b)=>a-b);try{await download(await exportPdfBytes(indexes),state.fileName.replace(/\.pdf$/i,'')+'-extracted.pdf');toast(`${indexes.length} pages extracted`);}catch(e){errorToast('Could not extract pages.');}});
$('#clearAllBtn').addEventListener('click',()=>{if(confirm('Clear the current document and all edits?'))resetApp();});$('#newPdfBtn').addEventListener('click',resetApp);
function resetApp(){state.bytes=null;state.pages=[];state.pdfjs=null;state.pdfDoc=null;state.history=[];state.future=[];els.editor.hidden=true;els.landing.hidden=false;els.save.disabled=true;els.download.disabled=true;}
function choosePdf(){ $('#pdfInput').click(); }$('#openPdfBtn').addEventListener('click',choosePdf);$('#uploadPdfBtn').addEventListener('click',choosePdf);$('#dropZone').addEventListener('click',choosePdf);$('#dropZone').addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' ')choosePdf();});$('#pdfInput').addEventListener('change',e=>{const f=e.target.files[0];if(f)f.arrayBuffer().then(b=>loadPdf(b,f.name));e.target.value='';});
['dragenter','dragover'].forEach(type=>$('#dropZone').addEventListener(type,e=>{e.preventDefault();$('#dropZone').classList.add('dragging')}));['dragleave','drop'].forEach(type=>$('#dropZone').addEventListener(type,e=>{e.preventDefault();$('#dropZone').classList.remove('dragging')}));$('#dropZone').addEventListener('drop',e=>{const f=[...e.dataTransfer.files].find(x=>x.type==='application/pdf'||x.name.endsWith('.pdf'));if(f)f.arrayBuffer().then(b=>loadPdf(b,f.name));else errorToast('Please drop a PDF file.');});
$('#mergePdfBtn').addEventListener('click',()=>$('#mergeInput').click());$('#mergeSidebarBtn').addEventListener('click',()=>$('#mergeInput').click());$('#mergeInput').addEventListener('change',async e=>{const files=[...e.target.files];if(!files.length)return;try{const out=await PDFDocument.create();for(const file of files){const doc=await PDFDocument.load(await file.arrayBuffer());const copied=await out.copyPages(doc,doc.getPageIndices());copied.forEach(p=>out.addPage(p));}await loadPdf(await out.save(),'merged-document.pdf');toast(`${files.length} PDFs merged locally`);}catch(err){errorToast('One of the selected PDFs could not be merged.');}e.target.value='';});
$('#themeToggle').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('pdfly-theme',document.body.classList.contains('dark')?'dark':'light');});if(localStorage.getItem('pdfly-theme')==='dark')document.body.classList.add('dark');
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();if(!els.download.disabled)$('#downloadBtn').click();}if(e.key==='Delete'&&state.tool==='select'){const p=currentPage();if(p?.annotations.some(a=>a.selected))mutate(()=>{p.annotations=p.annotations.filter(a=>!a.selected);});}});
window.addEventListener('resize',()=>{if(state.pages.length)renderPage();});
